---
- hosts: all
  become: true
  vars:
    ansible_become_pass: gns3

  tasks:
  - name: install openssh-server package
    become: yes
    apt: name=openssh-server state=latest update_cache=yes

  - name: start openssh-server
    shell: "vfstpd &"

